R/funs-string.R, R/separate.R, tests/tinytest/setup.R, tests/tinytest/test_separate.R, tests/tinytest/test_separate_lazy.R
Related to #2. Merge once https://github.com/pola-rs/r-polars/pull/397 is merged
=> Support `separate()` for `LazyFrame`

NEWS.md, R/filter.R, R/mutate.R, R/print.R, R/slice.R, R/summarize.R, R/utils.R, man/filter.DataFrame.Rd, man/mutate.DataFrame.Rd, man/slice_tail.DataFrame.Rd, man/summarize.DataFrame.Rd, tests/tinytest/test_by.R, tests/tinytest/test_by_lazy.R, tests/tinytest/test_filter.R, tests/tinytest/test_filter_lazy.R, tests/tinytest/test_mutate.R, tests/tinytest/test_mutate_lazy.R, tests/tinytest/test_slice.R, tests/tinytest/test_slice_lazy.R, tests/tinytest/test_summarize.R, tests/tinytest/test_summarize_lazy.R
Close #28 
``` r
library(dplyr, warn.conflicts = FALSE)
library(tidypolars)
#> Registered S3 method overwritten by 'tidypolars':
#>   method          from  
#>   print.DataFrame polars
iris |>
as_polars() |> 
filter(Sepal.Length == max(Sepal.Length), .by = Species)
#> shape: (3, 5)
#> ┌──────────────┬─────────────┬──────────────┬─────────────┬────────────┐
#> │ Sepal.Length ┆ Sepal.Width ┆ Petal.Length ┆ Petal.Width ┆ Species    │
#> │ ---          ┆ ---         ┆ ---          ┆ ---         ┆ ---        │
#> │ f64          ┆ f64         ┆ f64          ┆ f64         ┆ cat        │
#> ╞══════════════╪═════════════╪══════════════╪═════════════╪════════════╡
#> │ 5.8          ┆ 4.0         ┆ 1.2          ┆ 0.2         ┆ setosa     │
#> │ 7.0          ┆ 3.2         ┆ 4.7          ┆ 1.4 …
```
=> Implement `by` and `.by`

R/join.R, R/print.R, tests/tinytest/test_join_mutating.R, tests/tinytest/test_join_mutating_lazy.R
=> joins: better checks and error messages, more tests

NEWS.md, R/funs-string.R, R/utils-expr.R, R/utils.R, tests/tinytest/test_funs_string.R, tests/tinytest/test_funs_string_lazy.R
=> Implement `stringr::regex()`

NEWS.md, R/join.R, man/left_join.RPolarsDataFrame.Rd, man/semi_join.RPolarsDataFrame.Rd, tests/tinytest/test_join_mutating.R, tests/tinytest/test_join_mutating_lazy.R
=> Implement argument `relationship` for joins

NEWS.md, R/funs-date.R, R/utils-expr.R, tests/tinytest/test_funs_date.R, tests/tinytest/test_funs_date_lazy.R
=> Add support for `lubridate::make_date()`

NEWS.md, R/funs-default.R, tests/tinytest/test_funs_math.R, tests/tinytest/test_funs_math_lazy.R, tests/tinytest/test_mutate.R, tests/tinytest/test_mutate_lazy.R, tests/tinytest/test_rowwise.R, tests/tinytest/test_rowwise_lazy.R, vignettes/r-and-polars-expressions.Rmd
=> More support for `na.rm`

DESCRIPTION, R/funs-string.R, R/utils-expr.R, tests/testthat.R, tests/testthat/helper.R, tests/testthat/setup.R, tests/testthat/test-funs-date.R, tests/testthat/test-funs-string.R, tests/testthat/test-read-write.R
=> Add infrastructure for property-based testing

NEWS.md, R/arrange.R, R/funs-default.R, R/utils-expr.R, man/arrange.RPolarsDataFrame.Rd, tests/testthat/test-arrange-lazy.R, tests/testthat/test-arrange.R
Close #143 
Need to fix the case for character variables since that doesn't work with `-`
=> feat: better handling of expressions in `arrange()`

NEWS.md, R/funs-string.R, tests/testthat/_snaps/funs_string-lazy.md, tests/testthat/_snaps/funs_string.md, tests/testthat/test-funs_string-lazy.R, tests/testthat/test-funs_string.R, vignettes/r-and-polars-expressions.Rmd
To support our discussion in #132
=> feat: implement `stringr::str_replace_na()`

NEWS.md, R/complete.R, R/funs-string.R, tests/testthat/test-funs-string-lazy.R, tests/testthat/test-funs-string.R
=> fix: proper testing of `str_sub()` and `substr()`

NEWS.md, R/complete.R, R/funs-default.R, tests/testthat/test-funs_other-lazy.R, tests/testthat/test-funs_other.R
=> feat: Add partial support for `seq()`

R/funs-string.R
=> fix: another edge case for `str_sub()`

tests/testthat/test-funs-date-lazy.R, tests/testthat/test-funs-date.R
=> fix: Add right bound for datetime in test

NEWS.md, R/utils-expr.R, tests/testthat/_snaps/explicit_namespace-lazy.md, tests/testthat/_snaps/explicit_namespace.md, tests/testthat/_snaps/non-translated-lazy.md, tests/testthat/_snaps/non-translated.md
=> feat: Suggest opening an issue when encountering an untranslated function

NEWS.md, R/utils-expr.R, tests/testthat/test-magrittr-pipe-lazy.R, tests/testthat/test-magrittr-pipe.R
=> feat: Add support for `%>%` in expressions

NEWS.md, R/sink.R, man/sink_csv.Rd, man/sink_ipc.Rd, man/sink_ndjson.Rd, man/sink_parquet.Rd
=> feat: Add support for `mkdir` in all `sink_*()` functions

README.Rmd, README.md
Fixes #229 
@eitsupi if you have some time, could you take a quick look just to be sure I'm not writing anything wrong about the other tools (e.g. `arrow`, which you know more). Also, by any chance, have you used `sparklyr` before? I don't have anything to say about it.
=> docs: Add section "Related work" in the README

NEWS.md, R/funs-string.R, tests/testthat/test-funs_string-lazy.R, tests/testthat/test-funs_string.R, vignettes/r-and-polars-expressions.Rmd
=> feat: Add support for `gsub()`

NEWS.md, R/funs-date.R, tests/testthat/_snaps/funs_date-lazy.md, tests/testthat/_snaps/funs_date.md, tests/testthat/test-funs-date-lazy.R, tests/testthat/test-funs-date.R, tests/testthat/test-funs_date-lazy.R, tests/testthat/test-funs_date.R, vignettes/r-and-polars-expressions.Rmd
=> feat: Add support for `lubridate` functions `rollbackward()`, `rollback()`, and `rollforward()`
